# Set the base image
FROM node:latest

# Set the working directory
WORKDIR /app

# First copy the package.json file to the working directory
COPY package.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the files to the working directory
COPY . .

# ENV variables
ENV PORT=8080

# Expose the port
EXPOSE 8080

# Start the server
CMD ["npm", "start"]
